<?php

#####################################################
#	Glossaires version 2.0 pour xoops 2.X
#	Copyright 2003, Martial Le Peillet
#	webmaster@toplenet.com - http://www.toplenet.com
#
#	Module Original :
#	Glossaire version 2.2 pour Xoops 2.0
#	Copyright © 2002, Pascal Le Boustouller
#
#  Licence : GPL
#  Merci de laisser ce copyright en place...
#####################################################

$modversion['name'] = _MI_GLO_NAME;
$modversion['version'] = 2.2;
$modversion['description'] = _MI_GLO_DESC;
$modversion['credits'] = 'Module original : Pascal Le Boustoufler - V1.6 <br> Martial Le Peillet - toplenet.com - Ajout de catégories V2.0';
$modversion['author'] = 'Martial Le Peillet - webmaster@toplenet.com';
$modversion['help'] = 'glossaires.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'slogo_glossaires.png';
$modversion['dirname'] = 'glossaires';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file'] = 'glossaires_rand.php';
$modversion['blocks'][1]['name'] = _MI_GLO_BNAME1;
$modversion['blocks'][1]['show_func'] = 'glossaires_showrand';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _PRODEF;
$modversion['sub'][1]['url'] = 'index.php?pa=Propose';
$modversion['sub'][2]['name'] = _ASKDEF;
$modversion['sub'][2]['url'] = 'index.php?pa=Demande';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix! - permet la suppression des tables à la désinstallation du module.)
$modversion['tables'][0] = 'glossaires';
$modversion['tables'][1] = 'glossaires_cat';
$modversion['tables'][2] = 'glossaires_comm';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'glossaires_search';
